{
  "original_file": "c:\\Users\\patra\\Genesis FINAL TRY\\interface\\genesis_gui_launcher.py",
  "quarantine_timestamp": "2025-06-21T04:33:29.191326+00:00",
  "violations": [
    {
      "rule_type": "no_mock_data",
      "pattern": "test_",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\interface\\genesis_gui_launcher.py",
      "line_numbers": [
        352,
        353
      ],
      "violation_count": 2
    },
    {
      "rule_type": "no_fallback_logic",
      "pattern": "try:",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\interface\\genesis_gui_launcher.py",
      "line_numbers": [
        159,
        206,
        240,
        245,
        272
      ],
      "violation_count": 10
    },
    {
      "rule_type": "no_fallback_logic",
      "pattern": "except Exception",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\interface\\genesis_gui_launcher.py",
      "line_numbers": [
        222,
        263,
        293,
        341,
        367
      ],
      "violation_count": 6
    },
    {
      "rule_type": "no_fallback_logic",
      "pattern": "else:",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\interface\\genesis_gui_launcher.py",
      "line_numbers": [
        435,
        440,
        454,
        464
      ],
      "violation_count": 4
    },
    {
      "rule_type": "eventbus_required",
      "pattern": "emit(",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\interface\\genesis_gui_launcher.py",
      "line_numbers": [
        113,
        590
      ],
      "violation_count": 2
    }
  ],
  "quarantine_reason": "ARCHITECT_MODE_VIOLATION"
}