{
  "original_file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\phase13_event_subscriber.py",
  "quarantine_timestamp": "2025-06-21T04:33:37.984264+00:00",
  "violations": [
    {
      "rule_type": "no_mock_data",
      "pattern": "test_",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\phase13_event_subscriber.py",
      "line_numbers": [
        85,
        207,
        214
      ],
      "violation_count": 3
    },
    {
      "rule_type": "no_fallback_logic",
      "pattern": "try:",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\phase13_event_subscriber.py",
      "line_numbers": [
        56,
        103,
        123,
        222
      ],
      "violation_count": 4
    },
    {
      "rule_type": "no_fallback_logic",
      "pattern": "except Exception",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\phase13_event_subscriber.py",
      "line_numbers": [
        62,
        117,
        192
      ],
      "violation_count": 3
    },
    {
      "rule_type": "no_fallback_logic",
      "pattern": "if not",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\phase13_event_subscriber.py",
      "line_numbers": [
        126,
        146,
        162
      ],
      "violation_count": 3
    },
    {
      "rule_type": "no_fallback_logic",
      "pattern": "else:",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\phase13_event_subscriber.py",
      "line_numbers": [
        113,
        188
      ],
      "violation_count": 2
    },
    {
      "rule_type": "eventbus_required",
      "pattern": "emit(",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\phase13_event_subscriber.py",
      "line_numbers": [
        47,
        242
      ],
      "violation_count": 2
    }
  ],
  "quarantine_reason": "ARCHITECT_MODE_VIOLATION"
}